language: go
go:
- 1.8.x

notifications:
  email: false

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=gearmanexporterbot
    - secure: GETvpQpzTXEXU0q3ZEYI8UFncgyvonKLYUPDQlHzCiWD9FTxJJOkfmXj7C0XqD7+qROzyQak/EK5ZnbuD6rTYxZbtFOJHA5xJKDytfqdP9KSZnqpMnLnnHi2wM9mVDXsJGqDuEC3SU2sMOPfAnWVjHZlDSs1EGC5n71005CFzdvKyug6waAMV58SyMtmKM05+20SlvHD2feOlZh5hmW8gLoxJ8uTJoVSbTidGHulFPNYheIbJeQxhxK0mYgTrZTf6LeRqWR/TWHF5xkWlJQ8jhNv3Y3UYiDURz3v5NRjSJnip2Vh/pFltNzRzmborBwhJaxdQu1dw6BOphK9BbIhj+ZJ/3l/4z827nOPTJOV8mtApl0TPft8U9+7iWeDlTPZgD9LAd1GO6zEPg55KOw18fbTK7LquIXr0V4DOWMtULUwUrk53zApyVisT9Ga6tsYWf+Qj+mVGqakbsyDV+l05fky0ZZ16aj9roSsXGROY5d4AHK/1Ael04R3GkSGevQIEnrlTjPbdwo7lLq9B7eCnxGgWA9GpXR1cF7seM7Oo6Ak8aFDkNYcABuuchZDo/vINJ+dkXro/1ZcL+na9uhgZ+/+LJzaiZpgpET1aR8ky/mMWS7PGxPgdSRkJ6+nKp7ri4QKzet1jk3MiEkpDlGjmJyPDKtVX/KyOyDXSZ09iAY=

install: true

script:
- make build
- make docker-build

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: C4X1zAtBeUJPBUmGx0mDCAGlGQCdu4p6sJwJ5F2HZoadfPE/V0dCRvhC8hm8TKVyesmtACXYSSqW07Sq6A9CCQkV1BsbYEEovPNN7aSmQccRxOF+podkrkYogj0eQl0SJ3/h8DR2Q81+vStxIsPSXJU2yS/8YXMLUfIXOoANcaAjfWBGyCLU1Pop8IIZwaWB3zGt8va0nsj989yaaUkcnoUjdYq4AybSW1MNNnyrN53iHmeyDfp+UvyPB0TTFBAYO5fUt1mYrMI/bFofHZEMwZY+dw7O30Vrhd+ksgDvSXpGUVxnEuQ910xCnXoOGYuZ3JkmV3khidSZ2ZjaYt6VzbakgLPfidprsK/FQibocC8QCI4c5efa3XaQhZF1u70Q4eL1kQjTWt4zhNFXWj6tZK+RnUQHMSHx67aUGCOOJFCUTPPJjPXg5tttAu7/Z8cOYWCzFW6FgKvaE+JfTxM1X/ngDFkgloI76mT26XZJzuPxSRQhhR+6K6ODI6DZb+Bot+mO/ZCCbmQ2+LD4dO6Iah4NlTq6fCIxQThmbgVeMEgWm0xnd7TU3GgBeOba6pdo6p97H0C/jvpDOgLVQe1q5MUAO6FMu3YaYJYbWW8FHMbMZc6rcjeBlqMbayZpc/n8irwFguYHezZotIpEekzjXnQL3CuGtLjsVB2aKKUSRvU=
    file:
      - gearman-exporter.linux.amd64
      - gearman-exporter.darwin.amd64
    on:
      repo: bakins/gearman-exporter
      tags: true
  - provider: script
    skip_cleanup: true
    script: make docker-push
    on:
      repo: bakins/gearman-exporter
      tags: true
